# Netlify configuration file

[build]
  command = "cd netlify/functions && npm install && cd ../../frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

# This is the redirect for your backend API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# This is the NEW catch-all redirect for the frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200